all:
  hosts:
    node-0:
      ansible_host: 192.168.1.100
      ip: 192.168.1.100
      access_ip: 192.168.1.100
    node-1:
      ansible_host: 192.168.1.101
      ip: 192.168.1.101
      access_ip: 192.168.1.101
    node-2:
      ansible_host: 192.168.1.102
      ip: 192.168.1.102
      access_ip: 192.168.1.102
  children:
    kube_control_plane:
      hosts:
        node-0:
        node-1:
    kube_node:
      hosts:
        node-0:
        node-1:
        node-2:
    etcd:
      hosts:
        node-0:
        node-1:
        node-2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
