---
- name: Common tasks for every playbook
  import_playbook: boilerplate.yml

- name: Gather facts
  import_playbook: facts.yml

- name: Configure ephemeral tmpfs storage on Kubernetes nodes
  hosts: all
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  become: yes
  become_user: root  # Ensure you're using root for mounting tmpfs

  tasks:
    - name: Create directories for ephemeral storage
      file:
        path: "/tmp/{{ item }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      with_items:
        - vol1
        - vol2
        - vol3

    - name: Mount tmpfs on each directory without fstab modification
      become: yes
      mount:
        path: "/tmp/{{ item }}"
        src: "tmpfs"
        fstype: "tmpfs"
        opts: "size=5G"
        state: mounted
        dump: 0
        passno: 0
      with_items:
        - vol1
        - vol2
        - vol3
